# Tuwaiq Academy Competition

# 1. Data Exploration:



Read Dataset

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
df = pd.read_csv('Train.csv')

EDA

In [ ]:
df.head()

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,Program Presentation Method,Program Start Date,Program End Date,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working,Y
0,4f14c50d-162e-4a15-9cf0-ec129c33bcf0,37.0,ذكر,منطقة الرياض,الرياض,453686d8-4023-4506-b2df-fac8b059ac26,PCRF,PCRF,NaN,NaN,حضوري,5/28/2023,6/8/2023,12,نعم,البكالوريوس,هندسة حاسب الالي,NaN,2.44,4.0,غير موظف,NaN,NaN,0
1,0599d409-876b-41a5-af05-749ef0e77d32,21.0,ذكر,منطقة عسير,خميس مشيط,cc8e4e42-65d5-4fa1-82f9-6c6c2d508b60,APMR,SWPS,NaN,متوسط,حضوري,4/2/2023,4/6/2023,5,نعم,البكالوريوس,الإذاعة والتلفزيون والفيلم,الفنون والعلوم الإنسانية,5.00,5.0,طالب,NaN,NaN,0
2,38a11c0e-4afc-4261-9c64-e94cc0a272fb,24.0,ذكر,منطقة الرياض,الرياض,e006900d-05a9-4c2b-a36f-0ffb9fce44cd,APMR,NaN,NaN,متوسط,حضوري,7/23/2023,9/14/2023,54,نعم,البكالوريوس,Information Technology,NaN,3.50,5.0,موظف,NaN,NaN,0
3,1693e85b-f80e-40ce-846f-395ddcece6d3,23.0,ذكر,منطقة الرياض,الرياض,2ec15f6b-233b-428a-b9f5-e40bc8d14cf9,TOSL,TOSL,NaN,NaN,حضوري,7/23/2023,8/24/2023,33,نعم,البكالوريوس,حوسبة تطبيقية - (مسار شبكات الحاسب),NaN,3.55,5.0,خريج,NaN,NaN,0
4,98a0e8d0-5f80-4634-afd8-322aa0902863,23.0,ذكر,منطقة الرياض,الرياض,d32da0e9-1aed-48c3-992d-a22f9ccc741e,CAUF,SWPS,تقليدية,متوسط,حضوري,4/30/2023,6/22/2023,54,لا,البكالوريوس,نظم المعلومات الحاسوبية,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,NaN,NaN,NaN,0

In [ ]:
df.tail()

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,Program Presentation Method,Program Start Date,Program End Date,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working,Y
6543,cd196579-9590-441b-8787-41078f3cee25,31.0,أنثى,منطقة الرياض,الرياض,4f8c696a-b783-4d40-9776-105f6d3bd624,CAUF,SWPS,NaN,NaN,حضوري,4/2/2023,6/6/2023,66,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.40,5.0,NaN,NaN,NaN,0
6544,37bfc11c-ff8c-42dc-9cf9-0d13bb8f7131,27.0,أنثى,منطقة القصيم,بريدة,e94942dd-8684-4746-97ae-df567b9b0a4a,PCRF,PCRF,NaN,مبتدئ,عن بعد,5/14/2023,5/25/2023,12,نعم,البكالوريوس,علوم الحاسب,NaN,4.46,5.0,موظف,NaN,NaN,0
6545,fc114302-a79f-439f-a08b-fe0a51cf839e,24.0,أنثى,منطقة الرياض,الرياض,02ae0b47-64a6-47a1-b3c5-c0e4df393c30,PCRF,PCRF,تقليدية,مبتدئ,حضوري,7/16/2023,7/20/2023,5,لا,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.93,5.0,موظف,دوام كامل,Yes,1
6546,4b6d9a36-4402-4c75-bc3a-fca927dbaf65,25.0,ذكر,منطقة الرياض,الرياض,9b4cedaa-fac0-4eac-aa4b-b05b6a0c97ff,PCRF,PCRF,NaN,متوسط,حضوري,1/7/2024,1/18/2024,12,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,4.0,غير موظف,تدريب,No,0
6547,008f3386-0d43-45a4-8372-b282e5a0101a,37.0,أنثى,منطقة الرياض,الرياض,d8fbc53c-e042-4e45-b8c7-42b4ad0528ee,CAUF,NaN,NaN,مبتدئ,حضوري,3/19/2023,3/23/2023,5,نعم,الماجستير,دراسات وقضايا معاصرة,NaN,4.32,5.0,موظف,NaN,NaN,0

In [ ]:
len(df)

6548

In [ ]:
df.shape

(6548, 24)

In [ ]:
df.describe()

,Age,Program Days,University Degree Score,University Degree Score System,Y
count,6456.000000,6548.000000,6467.000000,6467.000000,6548.000000
mean,26.831165,19.691662,8.224432,9.773929,0.158674
std,5.535967,32.112061,19.120384,21.259962,0.365400
min,18.000000,3.000000,0.000000,4.000000,0.000000
25%,23.000000,5.000000,3.300000,5.000000,0.000000
50%,25.000000,12.000000,4.000000,5.000000,0.000000
75%,29.000000,19.000000,4.510000,5.000000,0.000000
max,57.000000,292.000000,100.000000,100.000000,1.000000

##Data preprocessing

In [ ]:
df.duplicated().sum()

48

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.shape

(6500, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6500 entries, 0 to 6547
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Student ID                      6500 non-null   object
 1   Age                             6413 non-null   float64
 2   Gender                          6500 non-null   object
 3   Home Region                     6498 non-null   object
 4   Home City                       6498 non-null   object
 5   Program ID                      6500 non-null   object
 6   Program Main Category Code      6500 non-null   object
 7   Program Sub Category Code       5580 non-null   object
 8   Technology Type                 3542 non-null   object
 9   Program Skill Level             4855 non-null   object
 10  Program Presentation Method     6500 non-null   object
 11  Program Start Date              6500 non-null   object
 12  Program End Date                6500 non-null   object
 13  Program Days                    6500 non-null   int64
 14  Completed Degree                6500 non-null   object
 15  Level of Education              6478 non-null   object
 16  Education Speaciality           6228 non-null   object
 17  College                         2638 non-null   object
 18  University Degree Score         6424 non-null   float64
 19  University Degree Score System  6424 non-null   float64
 20  Employment Status               5943 non-null   object
 21  Job Type                        1965 non-null   object
 22  Still Working                   1965 non-null   object
 23  Y                               6500 non-null   int64
dtypes: float64(3), int64(2), object(19)
memory usage: 1.2+ MB

We are drop this column because it will not effect in the model result and it has many missing value

In [ ]:
#drop Home City , Technology Type, College , Job Type, Still Working
df = df.drop(['Home City','Technology Type', 'College', 'Job Type', 'Still Working'], axis=1)

In [ ]:
df.isna().sum()

Student ID                           0
Age                                 87
Gender                               0
Home Region                          2
Program ID                           0
Program Main Category Code           0
Program Sub Category Code          920
Program Skill Level               1645
Program Presentation Method          0
Program Start Date                   0
Program End Date                     0
Program Days                         0
Completed Degree                     0
Level of Education                  22
Education Speaciality              272
University Degree Score             76
University Degree Score System      76
Employment Status                  557
Y                                    0
dtype: int64

By splitting the 'Program Start Date' and 'Program End Date' columns into various parts (year, month, day), we created additional features that might contain valuable information, potentially influencing the predictive outcomes of our model.

In [ ]:
df['Program Start Date'] = pd.to_datetime(df['Program Start Date'])
df['Program End Date'] = pd.to_datetime(df['Program End Date'])
df['Start_year'] = df['Program Start Date'].dt.year
df['Start_month'] = df['Program Start Date'].dt.month
df['Start_day'] = df['Program Start Date'].dt.day
df['End_year'] = df['Program End Date'].dt.year
df['End_month'] = df['Program End Date'].dt.month
df['End_day'] = df['Program End Date'].dt.day
df = df.drop(['Program Start Date','Program End Date', 'Program ID'], axis=1)
df.head()

,Student ID,Age,Gender,Home Region,Program Main Category Code,Program Sub Category Code,Program Skill Level,Program Presentation Method,Program Days,Completed Degree,Level of Education,Education Speaciality,University Degree Score,University Degree Score System,Employment Status,Y,Start_year,Start_month,Start_day,End_year,End_month,End_day
0,4f14c50d-162e-4a15-9cf0-ec129c33bcf0,37.0,ذكر,منطقة الرياض,PCRF,PCRF,NaN,حضوري,12,نعم,البكالوريوس,هندسة حاسب الالي,2.44,4.0,غير موظف,0,2023,5,28,2023,6,8
1,0599d409-876b-41a5-af05-749ef0e77d32,21.0,ذكر,منطقة عسير,APMR,SWPS,متوسط,حضوري,5,نعم,البكالوريوس,الإذاعة والتلفزيون والفيلم,5.00,5.0,طالب,0,2023,4,2,2023,4,6
2,38a11c0e-4afc-4261-9c64-e94cc0a272fb,24.0,ذكر,منطقة الرياض,APMR,NaN,متوسط,حضوري,54,نعم,البكالوريوس,Information Technology,3.50,5.0,موظف,0,2023,7,23,2023,9,14
3,1693e85b-f80e-40ce-846f-395ddcece6d3,23.0,ذكر,منطقة الرياض,TOSL,TOSL,NaN,حضوري,33,نعم,البكالوريوس,حوسبة تطبيقية - (مسار شبكات الحاسب),3.55,5.0,خريج,0,2023,7,23,2023,8,24
4,98a0e8d0-5f80-4634-afd8-322aa0902863,23.0,ذكر,منطقة الرياض,CAUF,SWPS,متوسط,حضوري,54,لا,البكالوريوس,نظم المعلومات الحاسوبية,4.00,5.0,NaN,0,2023,4,30,2023,6,22

In [ ]:
df.describe()

,Age,Program Days,University Degree Score,University Degree Score System,Y,Start_year,Start_month,Start_day,End_year,End_month,End_day
count,6413.000000,6500.000000,6424.000000,6424.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000
mean,26.822236,19.661692,8.242163,9.792964,0.159846,2022.795692,6.523538,14.635538,2022.830615,6.724000,14.450154
std,5.535534,32.189476,19.153997,21.297309,0.366492,0.435160,3.541663,8.773444,0.448023,3.527241,8.274180
min,18.000000,3.000000,0.000000,4.000000,0.000000,2022.000000,1.000000,1.000000,2022.000000,1.000000,1.000000
25%,23.000000,5.000000,3.300000,5.000000,0.000000,2023.000000,3.000000,7.000000,2023.000000,3.000000,8.000000
50%,25.000000,12.000000,4.000000,5.000000,0.000000,2023.000000,7.000000,14.000000,2023.000000,7.000000,15.000000
75%,29.000000,19.000000,4.510000,5.000000,0.000000,2023.000000,10.000000,22.000000,2023.000000,10.000000,21.000000
max,57.000000,292.000000,100.000000,100.000000,1.000000,2024.000000,12.000000,31.000000,2024.000000,12.000000,31.000000

The code separates the categorical columns and the numeric columns into two separate lists to handle them as appropriate, except for specific columns ("Student ID" and "Y") because Student ID has no effect and Y is the target.

In [ ]:
categorical_cols = df.select_dtypes(include=['object']).columns
categorical_cols = categorical_cols.drop('Student ID')
numerical_cols = df.select_dtypes(include=['number']).columns
numerical_cols = numerical_cols.drop('Y')
print(categorical_cols)
print(numerical_cols)

Index(['Gender', 'Home Region', 'Program Main Category Code',
       'Program Sub Category Code', 'Program Skill Level',
       'Program Presentation Method', 'Completed Degree', 'Level of Education',
       'Education Speaciality', 'Employment Status'],
      dtype='object')
Index(['Age', 'Program Days', 'University Degree Score',
       'University Degree Score System', 'Start_year', 'Start_month',
       'Start_day', 'End_year', 'End_month', 'End_day'],
      dtype='object')

# Numerical Processing:

*Check* for null values

In [ ]:
df[numerical_cols].isna().sum()

Age                               87
Program Days                       0
University Degree Score           76
University Degree Score System    76
Start_year                         0
Start_month                        0
Start_day                          0
End_year                           0
End_month                          0
End_day                            0
dtype: int64

There are missing values  in these two columns, so we fill them using the Mean.

In [ ]:
from math import floor
df['Age'].fillna(floor(df['Age'].mean()), inplace=True)
df['University Degree Score'].fillna(df['University Degree Score'].mean(), inplace=True)
df['University Degree Score System'].fillna(5, inplace=True)

In [ ]:
df[numerical_cols]

,Age,Program Days,University Degree Score,University Degree Score System,Start_year,Start_month,Start_day,End_year,End_month,End_day
0,37.0,12,2.44,4.0,2023,5,28,2023,6,8
1,21.0,5,5.00,5.0,2023,4,2,2023,4,6
2,24.0,54,3.50,5.0,2023,7,23,2023,9,14
3,23.0,33,3.55,5.0,2023,7,23,2023,8,24
4,23.0,54,4.00,5.0,2023,4,30,2023,6,22
...,...,...,...,...,...,...,...,...,...,...
6543,31.0,66,4.40,5.0,2023,4,2,2023,6,6
6544,27.0,12,4.46,5.0,2023,5,14,2023,5,25
6545,24.0,5,4.93,5.0,2023,7,16,2023,7,20
6546,25.0,12,4.00,4.0,2024,1,7,2024,1,18
6547,37.0,5,4.32,5.0,2023,3,19,2023,3,23

Scaling (min-max)

We performed feature scaling using the Min-Max scaling technique on numerical columns. This operation transforms the data so that each feature falls within the range [0, 1]. It's particularly useful when the features have different ranges, which could potentially bias the learning algorithm towards features with larger magnitudes.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


df[numerical_cols] = scaler.fit_transform(df[numerical_cols])
df[numerical_cols]

,Age,Program Days,University Degree Score,University Degree Score System,Start_year,Start_month,Start_day,End_year,End_month,End_day
0,0.487179,0.031142,0.0244,0.000000,0.5,0.363636,0.900000,0.5,0.454545,0.233333
1,0.076923,0.006920,0.0500,0.010417,0.5,0.272727,0.033333,0.5,0.272727,0.166667
2,0.153846,0.176471,0.0350,0.010417,0.5,0.545455,0.733333,0.5,0.727273,0.433333
3,0.128205,0.103806,0.0355,0.010417,0.5,0.545455,0.733333,0.5,0.636364,0.766667
4,0.128205,0.176471,0.0400,0.010417,0.5,0.272727,0.966667,0.5,0.454545,0.700000
...,...,...,...,...,...,...,...,...,...,...
6543,0.333333,0.217993,0.0440,0.010417,0.5,0.272727,0.033333,0.5,0.454545,0.166667
6544,0.230769,0.031142,0.0446,0.010417,0.5,0.363636,0.433333,0.5,0.363636,0.800000
6545,0.153846,0.006920,0.0493,0.010417,0.5,0.545455,0.500000,0.5,0.545455,0.633333
6546,0.179487,0.031142,0.0400,0.000000,1.0,0.000000,0.200000,1.0,0.000000,0.566667
6547,0.487179,0.006920,0.0432,0.010417,0.5,0.181818,0.600000,0.5,0.181818,0.733333

# Categorical Preprocessing:

Check for null values

In [ ]:
df[categorical_cols].isna().sum()

Gender                            0
Home Region                       2
Program Main Category Code        0
Program Sub Category Code       920
Program Skill Level            1645
Program Presentation Method       0
Completed Degree                  0
Level of Education               22
Education Speaciality           272
Employment Status               557
dtype: int64

Print the unique value for all columns

In [ ]:
print("Unique values for each column:\n")
for col in categorical_cols:
    print(col+':', len(df[df[col].notna()][col].unique()))


print("\n\nExamples\n")
for col in categorical_cols:
    l = len(df[df[col].notna()][col].unique())
    if l > 15:
        print(col+':', df[df[col].notna()][col].unique()[:5])
        continue
    print(col+':', df[df[col].notna()][col].unique())

Unique values for each column:

Gender: 2
Home Region: 13
Program Main Category Code: 10
Program Sub Category Code: 11
Program Skill Level: 3
Program Presentation Method: 2
Completed Degree: 2
Level of Education: 5
Education Speaciality: 871
Employment Status: 6


Examples

Gender: ['ذكر' 'أنثى']
Home Region: ['منطقة الرياض' 'منطقة عسير' 'المنطقة الشرقية' 'منطقة مكة المكرمة'
 'منطقة نجران' 'منطقة المدينة المنورة' 'منطقة القصيم' 'منطقة تبوك'
 'منطقة الحدود الشمالية' 'منطقة جازان' 'منطقة الباحة' 'منطقة حائل'
 'منطقة الجوف']
Program Main Category Code: ['PCRF' 'APMR' 'TOSL' 'CAUF' 'ABIR' 'GRST' 'INFA' 'SERU' 'QWLM' 'DTFH']
Program Sub Category Code: ['PCRF' 'SWPS' 'TOSL' 'INFA' 'SRTA' 'CRDP' 'KLTM' 'ERST' 'ASCW' 'QTDY'
 'ABIR']
Program Skill Level: ['متوسط' 'مبتدئ' 'متقدم']

one hot:

`Gender`

`Technology Type`

`Program Skill Level`

`Program Presentation Method`

`Completed Degree`

`Level of Education`

`Education Speaciality`

`Employment Status`

`Job Type`

`Still Working`

Label encoding:

`Home Region`

`Home City`

`Program Main Category Code`

`Program Sub Category Code`

`College`

### Label encoding columns:

Label encoding columns to convert categorical data into a format that can be provided to machine learning algorithms for training.

In [ ]:
For_label_enc_col = ['Home Region','Program Main Category Code',
                     'Program Sub Category Code']
df[For_label_enc_col]

Fill nulls by using bfill and ffill techniques

In [ ]:
# Fill nulls
for col in For_label_enc_col:
    df[col].fillna(method='bfill', inplace=True)
    df[col].fillna(method='ffill', inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for col in For_label_enc_col:
    label_encoders[col] = LabelEncoder()
    df[col] = label_encoders[col].fit_transform(df[col])

df[For_label_enc_col]

### one hot encoding columns:
In this technique, each category in a categorical variable is represented by a binary (0 or 1) column

In [ ]:
gender = pd.get_dummies(df['Gender'],drop_first=True, dtype=int)
gender

Fill null values for Program Skill Level by using bfill and ffill

In [ ]:
df['Program Skill Level'].fillna(method='bfill', inplace=True)
df['Program Skill Level'].fillna(method='ffill', inplace=True)
prog_skill = pd.get_dummies(df['Program Skill Level'],drop_first=True, dtype=int)
prog_skill

In [ ]:
prog_pres = pd.get_dummies(df['Program Presentation Method'],drop_first=True, dtype=int)
prog_pres

In [ ]:
degree = pd.get_dummies(df['Completed Degree'],drop_first=True, dtype=int)
degree.rename(columns={'نعم': 'degree_completed'}, inplace=True)
degree

Fill null values for level of education by using bfill and ffill

In [ ]:
df['Level of Education'].fillna(method='bfill',inplace=True)
df['Level of Education'].fillna(method='ffill', inplace=True)
edu_lvl_class = ['البكالوريوس', 'الماجستير', 'ثانوي', 'الدكتوراه','غير معروف']
for i in range(len(df)):
    lvl = str(df['Level of Education'].iloc[i]).lower()
    if lvl not in edu_lvl_class:
        df['Level of Education'].iloc[i] = 'غير معروف'

edu_lvl = pd.get_dummies(df['Level of Education'], drop_first=True, dtype=int)
edu_lvl

In [ ]:
df['Level of Education'].fillna(method='bfill', inplace=True)
df['Level of Education'].fillna(method='ffill', inplace=True)

# Categorical encoding
tech_majors = ['حاسب',  'معلومات','تقنية', 'بيانات', 'cis', 'computer', 'اتصالات','it', 'شبكات','software','رقمي','network','mis','مواقع','cs',
            'برمجيات', 'امن سيبراني','اكترونيات', 'سيبراني', 'لكترونيات','ذكاء','data', 'information', 'technology','communication','حوسب','حاسب'
            ,'كمبيوتر','برمجه','gis','computing','conputer', 'لكتروني','artificial','artificial','artifical intelligence','صطناعي','سبراني','تكنولوجيا','ويب','وسائط',
            'برمجة','artifical','web','system','iot','programming','softeare','تطوير','multimedia','الحاشب']

for i in range(len(df)):
    maj = str(df['Education Speaciality'].iloc[i]).lower()
    if any(word in maj for word in tech_majors):
        df['Education Speaciality'].iloc[i] = 'تقني'
    else:
        df['Education Speaciality'].iloc[i] = 'غير تقني'


edu_spe = pd.get_dummies(df['Education Speaciality'], drop_first=True, dtype=int)
edu_spe.rename(columns={'غير تقني': 'Technial or not'}, inplace=True)

edu_spe

In [ ]:
df['Employment Status'].fillna(method='bfill', inplace=True)
df['Employment Status'].fillna(method='ffill', inplace=True)
emp_stat = pd.get_dummies(df['Employment Status'], drop_first=True, dtype=int)
emp_stat

In [ ]:
oneHot_col_df = pd.concat([gender,prog_skill,prog_pres,degree,edu_lvl,edu_spe,emp_stat],axis=1)
oneHot_col_df.head()

# Combine:
We created a new data frame that contains the scaled numerical columns, the specified columns for label encoding, the one-hot encoded columns, and the target variable 'Y'. This combined DataFrame was used for processing and modeling.

In [ ]:
y = df['Y']

processed_df = pd.concat([df[numerical_cols].copy(),df[For_label_enc_col],oneHot_col_df,y],axis=1)
processed_df

# Training:
This section focuses on the modeling process and compares the performance of Random Forest, Logistic Regression, and Ensemble Learning techniques. The main objective was to identify the most effective approach for our problem.
After evaluating the performance of Random Forest, Logistic Regression, and Ensemble Learning models, the Ensemble Learning approach achieved the highest result. The GridSearchCV further enhanced the performance by finding the optimal hyperparameters for the ensemble model.

Random Forest:

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_predict,train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report

# Split the dataset into training and test sets
X = processed_df.drop('Y', axis=1)
y = processed_df['Y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

# Apply SMOTE for dealing with class imbalance
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

# Logistic Regression Classifier
classifier = RandomForestClassifier()

# Define hyperparameters for RandomizedSearchCV
param_grid = {'max_depth': [10],
              'min_samples_leaf': [4],
              'min_samples_split': [2, 5, 10],
              'n_estimators': [400, 1000]}

# Perform RandomizedSearchCV
rf_random2 = RandomizedSearchCV(estimator=classifier, param_distributions=param_grid, scoring='f1', n_iter=100, cv=5, verbose=2, random_state=42, n_jobs=-1)
rf_random2.fit(X_train_res, y_train_res)

# Get the best model from RandomizedSearchCV
best_rf_model = rf_random2.best_estimator_

# Make predictions on the training and test sets
y_train_pred = best_rf_model.predict(X_train_res)
y_test_pred = best_rf_model.predict(X_test)

# Evaluate the model on both training and test sets
train_accuracy = accuracy_score(y_train_res, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print("Training Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

# Generate classification reports for both training and test sets
print("Training Classification Report:")
print(classification_report(y_train_res, y_train_pred))

print("Test Classification Report:")
print(classification_report(y_test, y_test_pred))

Logistic Regression:

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Split the dataset into training and test sets
X = processed_df.drop('Y', axis=1)
y = processed_df['Y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

# Apply SMOTE for dealing with class imbalance
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

# Logistic Regression Classifier
classifier = LogisticRegression()

# Define hyperparameters for RandomizedSearchCV
param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100]
}

# Perform RandomizedSearchCV
lr_random = RandomizedSearchCV(estimator=classifier, param_distributions=param_grid, scoring='f1', n_iter=100, cv=5, verbose=2, random_state=42, n_jobs=-1)
lr_random.fit(X_train_res, y_train_res)

# Get the best model from RandomizedSearchCV
best_lr_model = lr_random.best_estimator_

# Make predictions on the training and test sets
y_train_pred = best_lr_model.predict(X_train_res)
y_test_pred = best_lr_model.predict(X_test)

# Evaluate the model on both training and test sets
train_accuracy = accuracy_score(y_train_res, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print("Training Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

# Generate classification reports for both training and test sets
print("Training Classification Report:")
print(classification_report(y_train_res, y_train_pred))

print("Test Classification Report:")
print(classification_report(y_test, y_test_pred))

Ensemble:

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import TomekLinks
import numpy as np

X = processed_df.drop('Y', axis=1)
y = processed_df['Y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

# Handle NaN values in y_test
nan_indices = np.isnan(y_test)
X_test = X_test[~nan_indices]
y_test = y_test[~nan_indices]

smote = SMOTE(k_neighbors=5, sampling_strategy='auto', random_state=42)
tomek_links = TomekLinks(sampling_strategy='majority')

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
X_train_res, y_train_res = tomek_links.fit_resample(X_train_res, y_train_res)

rf_classifier = RandomForestClassifier(
    n_estimators=1000,
    max_depth=100,
    min_samples_split=2,
    min_samples_leaf=4,
    random_state=42
)
xgb_classifier = XGBClassifier(
    n_estimators=394,
    colsample_bytree=0.7123738038749523,
    gamma=0.27134804157912423,
    subsample=0.9947547746402069,
    learning_rate=0.052277267492428794,
    max_depth=9,
    min_child_weight=1,
    random_state=42
)

ensemble_model = VotingClassifier(estimators=[
    ('random_forest', rf_classifier),
    ('xgboost', xgb_classifier)
], voting='soft')

ensemble_model.fit(X_train_res, y_train_res)

# Training result
y_pred_train = ensemble_model.predict(X_train_res)
print("Ensemble Model Training Performance:")
print(classification_report(y_train_res, y_pred_train))
print("Training Accuracy:", accuracy_score(y_train_res, y_pred_train))

# Test result
y_pred_test = ensemble_model.predict(X_test)
print("Ensemble Model Test Performance:")
print(classification_report(y_test, y_pred_test))
print("Test Accuracy:", accuracy_score(y_test, y_pred_test))

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for grid search
param_grid = {
    'random_forest__n_estimators': [100, 500],
    'random_forest__max_depth': [50, 100],
    'xgboost__n_estimators': [200, 400],
    'xgboost__max_depth': [5, 10],
}

# Create the grid search object
grid_search = GridSearchCV(estimator=ensemble_model, param_grid=param_grid, scoring='accuracy')

# Perform grid search on the resampled training data
grid_search.fit(X_train_res, y_train_res)

# Get the best estimator and its associated parameters
best_estimator = grid_search.best_estimator_
best_params = grid_search.best_params_

# Print the best parameters
print("Best Parameters:", best_params)

# Training result with best estimator
y_pred_train = best_estimator.predict(X_train_res)
print("Ensemble Model Training Performance:")
print(classification_report(y_train_res, y_pred_train))
print("Training Accuracy:", accuracy_score(y_train_res, y_pred_train))

# Test result with best estimator
y_pred_test = best_estimator.predict(X_test)
print("Ensemble Model Test Performance:")
print(classification_report(y_test, y_pred_test))
print("Test Accuracy:", accuracy_score(y_test, y_pred_test))

# Test:
We use ensemble with gride search for testing

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
test = pd.read_csv('test.csv')

## Preprocess test data:

In [ ]:
# processing fun
def processing(df, label_encoders,scaler):

    df['Program Start Date'] = pd.to_datetime(df['Program Start Date'])
    df['Program End Date'] = pd.to_datetime(df['Program End Date'])
    df['Start_year'] = df['Program Start Date'].dt.year
    df['Start_month'] = df['Program Start Date'].dt.month
    df['Start_day'] = df['Program Start Date'].dt.day
    df['End_year'] = df['Program End Date'].dt.year
    df['End_month'] = df['Program End Date'].dt.month
    df['End_day'] = df['Program End Date'].dt.day
    df = df.drop(['Program Start Date','Program End Date', 'Program ID'], axis=1)

    #split categorical and numerical columns
    categorical_cols = df.select_dtypes(include=['object']).columns
    categorical_cols = categorical_cols.drop('Student ID')
    numerical_cols = df.select_dtypes(include=['number']).columns

    # Numerical:
    from math import floor
    df['Age'].fillna(floor(df['Age'].mean()), inplace=True)
    df['University Degree Score'].fillna(df['University Degree Score'].mean(), inplace=True)
    df['University Degree Score System'].fillna(5, inplace=True)
    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])
    df[numerical_cols]


    # categorical:
    ## label enc:
    For_label_enc_col = ['Home Region','Program Main Category Code',
                     'Program Sub Category Code']
    df[For_label_enc_col]

    for col in For_label_enc_col:
        df[col].fillna(method='bfill', inplace=True)
        df[col].fillna(method='ffill', inplace=True)


    for col in For_label_enc_col:
        df[col] = label_encoders[col].fit_transform(df[col])

    ## one hot enc:
    gender = pd.get_dummies(df['Gender'],drop_first=True, dtype=int)

    df['Program Skill Level'].fillna(method='bfill', inplace=True)
    df['Program Skill Level'].fillna(method='ffill', inplace=True)
    prog_skill = pd.get_dummies(df['Program Skill Level'],drop_first=True, dtype=int)

    prog_pres = pd.get_dummies(df['Program Presentation Method'],drop_first=True, dtype=int)

    degree = pd.get_dummies(df['Completed Degree'],drop_first=True, dtype=int)
    degree.rename(columns={'نعم': 'degree_completed'}, inplace=True)

    df['Level of Education'].fillna(method='bfill',inplace=True) # test contain different values
    df['Level of Education'].fillna(method='ffill', inplace=True)
    edu_lvl_class = ['البكالوريوس', 'الماجستير', 'ثانوي', 'الدكتوراه','غير معروف']
    for i in range(len(df)):
        lvl = str(df['Level of Education'].iloc[i]).lower()
        if lvl not in edu_lvl_class:
            df['Level of Education'].iloc[i] = 'غير معروف'

    edu_lvl = pd.get_dummies(df['Level of Education'], drop_first=True, dtype=int)
    df['Level of Education'].fillna(method='bfill', inplace=True) # test contain different values
    df['Level of Education'].fillna(method='ffill', inplace=True)


    tech_majors = ['حاسب',  'معلومات','تقنية', 'بيانات', 'cis', 'computer', 'اتصالات','it', 'شبكات','software','رقمي','network','mis','مواقع','cs',
                'برمجيات', 'امن سيبراني','اكترونيات', 'سيبراني', 'لكترونيات','ذكاء','data', 'information', 'technology','communication','حوسب','حاسب'
                ,'كمبيوتر','برمجه','gis','computing','conputer', 'لكتروني','artificial','artificial','artifical intelligence','صطناعي','سبراني','تكنولوجيا','ويب','وسائط',
                'برمجة','artifical','web','system','iot','programming','softeare','تطوير','multimedia','الحاشب']

    for i in range(len(df)):
        maj = str(df['Education Speaciality'].iloc[i]).lower()
        if any(word in maj for word in tech_majors):
            df['Education Speaciality'].iloc[i] = 'تقني'
        else:
            df['Education Speaciality'].iloc[i] = 'غير تقني'


    edu_spe = pd.get_dummies(df['Education Speaciality'], drop_first=True, dtype=int)
    edu_spe.rename(columns={'غير تقني': 'Technial or not'}, inplace=True)


    df['Employment Status'].fillna(method='bfill', inplace=True)
    df['Employment Status'].fillna(method='ffill', inplace=True)
    emp_stat = pd.get_dummies(df['Employment Status'], drop_first=True, dtype=int)


    oneHot_col_df = pd.concat([gender,prog_skill,prog_pres,degree,edu_lvl,edu_spe,emp_stat],axis=1)

    processed_df = pd.concat([df[numerical_cols],df[For_label_enc_col],oneHot_col_df],axis=1)

    return processed_df

# Submitions:

In [ ]:
test_data = processing(test, label_encoders,scaler)
y_pred = grid_search.predict(test_data)
submission = pd.DataFrame({'ID': list(range(1, len(test)+1)),
                    'Y': y_pred})


submission.to_csv('Submission.csv', index=False)